@startuml
title RawComponentDiagram
skinparam backgroundColor #FFFFFF
component CLIENT
component FRONTEND
component MIDDLE
component BACKEND
interface "HTTP" as proto
CLIENT ..> MTProto : use
MTProto - FRONTEND
FRONTEND .> HTTP : use
HTTP - MIDDLE
MIDDLE .> proto : use
proto - BACKEND
BACKEND -u.> DataSource
@enduml
